packages:
  - "cli/*"
  - "packages/*"
  - "examples/*"
  - "api/*"
  - "core/*"

# reference: https://pnpm.io/catalogs
catalog:
  "@parcel/bundler-default": "nightly"
  "@parcel/core": "nightly"
  "@parcel/diagnostic": "nightly"
  "@parcel/fs": "nightly"
  "@parcel/package-manager": "nightly"
  "@parcel/watcher": "2.4.1"
  "@parcel/hash": "2.9.3"
  "@parcel/plugin": "nightly"
  "@parcel/types": "nightly"
  "@parcel/graph": "3.2.0"
  "@parcel/logger": "nightly"
  "@parcel/utils": "nightly"
  "@parcel/events": "nightly"
  "@parcel/cache": "nightly"
  "@parcel/compressor-raw": "latest"
  "@parcel/config-default": "nightly"
  "@parcel/optimizer-data-url": "nightly"
  "@parcel/reporter-bundle-buddy": "latest"
  "@parcel/resolver-default": "nightly"
  "@parcel/runtime-js": "nightly"
  "@parcel/runtime-service-worker": "latest"
  "@parcel/transformer-babel": "nightly"
  "@parcel/transformer-css": "nightly"
  "@parcel/transformer-graphql": "nightly"
  "@parcel/transformer-inline-string": "nightly"
  "@parcel/transformer-js": "nightly"
  "@parcel/transformer-less": "nightly"
  "@parcel/transformer-postcss": "nightly"
  "@parcel/transformer-raw": "nightly"
  "@parcel/transformer-react-refresh-wrap": "nightly"
  "@parcel/transformer-sass": "nightly"
  "@parcel/transformer-svg-react": "nightly"
  "@parcel/transformer-worklet": "nightly"
  "@parcel/source-map": "2.1.1"
  "@parcel/workers": "nightly"
  "@parcel/node-resolver-core": "nightly"
