packages:
  - "cli/*"
  - "packages/*"
  - "examples/*"
  - "api/*"
  - "core/*"

# reference: https://pnpm.io/catalogs
catalog:
  "@parcel/bundler-default": "2.0.0-canary.1720"
  "@parcel/core": "2.0.0-canary.1720"
  "@parcel/diagnostic": "2.0.0-canary.1720"
  "@parcel/fs": "2.0.0-canary.1720"
  "@parcel/package-manager": "2.0.0-canary.1720"
  "@parcel/watcher": "2.4.1"
  "@parcel/hash": "2.9.3"
  "@parcel/plugin": "2.0.0-canary.1720"
  "@parcel/types": "2.0.0-canary.1720"
  "@parcel/graph": "3.2.0"
  "@parcel/logger": "2.0.0-canary.1720"
  "@parcel/utils": "2.0.0-canary.1720"
  "@parcel/events": "2.0.0-canary.1720"
  "@parcel/cache": "2.0.0-canary.1720"
  "@parcel/compressor-raw": "2.12.1-canary.3351"
  "@parcel/config-default": "2.0.0-canary.1720"
  "@parcel/optimizer-data-url": "2.0.0-canary.1720"
  "@parcel/reporter-bundle-buddy": "2.12.1-canary.3351"
  "@parcel/resolver-default": "2.0.0-canary.1720"
  "@parcel/runtime-js": "2.0.0-canary.1720"
  "@parcel/runtime-service-worker": "2.12.1-canary.3351"
  "@parcel/transformer-babel": "2.0.0-canary.1720"
  "@parcel/transformer-css": "2.0.0-canary.1720"
  "@parcel/transformer-graphql": "2.0.0-canary.1720"
  "@parcel/transformer-inline-string": "2.0.0-canary.1720"
  "@parcel/transformer-js": "2.0.0-canary.1720"
  "@parcel/transformer-less": "2.0.0-canary.1720"
  "@parcel/transformer-postcss": "2.0.0-canary.1720"
  "@parcel/transformer-raw": "2.0.0-canary.1720"
  "@parcel/transformer-react-refresh-wrap": "2.0.0-canary.1720"
  "@parcel/transformer-sass": "2.0.0-canary.1720"
  "@parcel/transformer-svg-react": "2.12.1-canary.3351"
  "@parcel/transformer-worklet": "2.12.1-canary.3351"
  "@parcel/source-map": "2.1.1"
  "@parcel/workers": "2.0.0-canary.1720"
  "@parcel/node-resolver-core": "3.3.1-nightly.3142"
